image: vmcswaggers-docker-local.artifactory.eng.vmware.com/diff-checker:0.0.3

before_script:
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global url."https://oauth2:${SDK_CLONE_ACCESS_TOKEN}@gitlab.eng.vmware.com/".insteadOf "https://gitlab.eng.vmware.com/"

stages:
  - check_modules
  - module_diff
  - sync

add_module_jobs:
  tags: [new-docker-runner]
  stage: check_modules
  script:
    - ./scripts/add_jobs.sh
  artifacts:
    paths:
      - .gitlab-ci/module-versioning.yml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "aagrawal3/main/automate-sementic-versioning" && $CI_COMMIT_TITLE != "Updated version.txt"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "aagrawal3/main/automate-sementic-versioning" && $CI_COMMIT_TITLE != "Updated version.txt"'

generate_module_diff:
  stage: module_diff
  needs:
    - add_module_jobs
  trigger:
    include:
      - artifact: .gitlab-ci/module-versioning.yml
        job: add_module_jobs
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "aagrawal3/main/automate-sementic-versioning" && $CI_COMMIT_TITLE != "Updated version.txt"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "aagrawal3/main/automate-sementic-versioning" && $CI_COMMIT_TITLE != "Updated version.txt"'

sync_with_release:
  tags: [new-docker-runner]
  stage: sync
  script:
    - ./scripts/sync_to_release.sh
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "aagrawal3/main/automate-sementic-versioning"'
