sync_<<module>>_to_release:
  tags: [new-docker-runner]
  stage: sync_with_release
  script:
    - echo "Next version passed from previous job - $NEXT_VERSION"
    - ./scripts/sync_to_release.sh $CI_COMMIT_SHA $NEXT_VERSION <<module_path>>
  rules:
    - changes:
      - "<<module_path>>/**/*"
