image: vmcswaggers-docker-local.artifactory.eng.vmware.com/diff-checker:0.0.3

before_script:
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global url."https://oauth2:${GO_SDK_PROJECT_ACCESS_TOKEN}@gitlab.eng.vmware.com/".insteadOf "https://gitlab.eng.vmware.com/"

stages:
  - generate_version
